import type { Tugas } from "../types/tugas"

export const DUMMY_TUGAS: Tugas[] = [
  {
    id: 1,
    judul: "Tugas Jaringan: Topologi dan Protokol",
    deskripsi:
      "Buatlah laporan tentang 5 jenis topologi jaringan beserta kelebihan dan kekurangannya. Sertakan juga penjelasan tentang protokol TCP/IP.",
    kelas_mengajar_id: 2,
    guru_nama: "Asep Nugraha",
    mata_pelajaran: "Dasar Jaringan",
    kelas: "X TKJ 2",
    lampiran: [
      { id: 1, nama: "panduan-topologi.pdf", ukuran: "1.2 MB", tipe: "application/pdf" },
    ],
    tanggal_dibuka: "2026-07-10",
    tenggat_waktu: "2026-07-17",
    tenggat_jam: "23:59",
    nilai_maksimal: 100,
    status: "Dipublikasikan",
    created_at: "2026-07-08T08:00:00Z",
    updated_at: "2026-07-10T08:00:00Z",
  },
  {
    id: 2,
    judul: "Praktikum MikroTik: Konfigurasi DHCP Server",
    deskripsi:
      "Lakukan konfigurasi DHCP Server pada perangkat MikroTik RouterOS. Dokumentasikan setiap langkah konfigurasi dan sertakan hasil pengujian.",
    kelas_mengajar_id: 3,
    guru_nama: "Rina Wulandari",
    mata_pelajaran: "Administrasi Sistem Jaringan",
    kelas: "XI TKJ 1",
    lampiran: [
      { id: 2, nama: "lab-dhcp-guide.pdf", ukuran: "3.5 MB", tipe: "application/pdf" },
      { id: 3, nama: "template-laporan.docx", ukuran: "245 KB", tipe: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
    ],
    tanggal_dibuka: "2026-07-12",
    tenggat_waktu: "2026-07-19",
    tenggat_jam: "23:59",
    nilai_maksimal: 100,
    status: "Dipublikasikan",
    created_at: "2026-07-11T09:00:00Z",
    updated_at: "2026-07-12T08:00:00Z",
  },
  {
    id: 3,
    judul: "Kuis HTML & CSS: Membuat Formulir",
    deskripsi:
      "Buat halaman HTML berisi formulir pendaftaran online dengan minimal 6 field input. Terapkan styling menggunakan CSS.",
    kelas_mengajar_id: 4,
    guru_nama: "Rina Wulandari",
    mata_pelajaran: "Pemrograman Web",
    kelas: "XI TBSM 1",
    lampiran: [],
    tanggal_dibuka: "2026-07-15",
    tenggat_waktu: "2026-07-18",
    tenggat_jam: "21:00",
    nilai_maksimal: 50,
    status: "Dipublikasikan",
    created_at: "2026-07-14T10:00:00Z",
    updated_at: "2026-07-15T08:00:00Z",
  },
  {
    id: 4,
    judul: "Tugas Basis Data: ERD Perpustakaan",
    deskripsi:
      "Buatlah Entity Relationship Diagram (ERD) untuk sistem perpustakaan sekolah. Minimal mencakup 5 entitas beserta relasinya.",
    kelas_mengajar_id: 5,
    guru_nama: "Budi Santoso",
    mata_pelajaran: "Basis Data",
    kelas: "XII TKJ 1",
    lampiran: [
      { id: 4, nama: "contoh-erd.pdf", ukuran: "890 KB", tipe: "application/pdf" },
    ],
    tanggal_dibuka: "2026-02-20",
    tenggat_waktu: "2026-02-27",
    tenggat_jam: "23:59",
    nilai_maksimal: 100,
    status: "Ditutup",
    created_at: "2026-02-15T08:00:00Z",
    updated_at: "2026-02-27T23:59:00Z",
  },
  {
    id: 5,
    judul: "Tugas Linux: Perintah Dasar Terminal",
    deskripsi:
      "Kerjakan latihan perintah dasar Linux terminal. Dokumentasikan setiap perintah beserta output-nya dalam bentuk screenshot.",
    kelas_mengajar_id: 6,
    guru_nama: "Siti Rahayu",
    mata_pelajaran: "Sistem Operasi",
    kelas: "X TBSM 1",
    lampiran: [
      { id: 5, nama: "latihan-linux.pdf", ukuran: "1.5 MB", tipe: "application/pdf" },
    ],
    tanggal_dibuka: "2026-07-05",
    tenggat_waktu: "2026-07-12",
    tenggat_jam: "23:59",
    nilai_maksimal: 75,
    status: "Ditutup",
    created_at: "2026-07-03T08:00:00Z",
    updated_at: "2026-07-12T23:59:00Z",
  },
  {
    id: 6,
    judul: "Proyek Akhir: Website Portfolio",
    deskripsi:
      "Buatlah website portfolio pribadi menggunakan HTML, CSS, dan JavaScript minimal 3 halaman. Upload ke GitHub Pages.",
    kelas_mengajar_id: 4,
    guru_nama: "Rina Wulandari",
    mata_pelajaran: "Pemrograman Web",
    kelas: "XI TBSM 1",
    lampiran: [],
    tanggal_dibuka: "2026-08-01",
    tenggat_waktu: "2026-08-31",
    tenggat_jam: "23:59",
    nilai_maksimal: 200,
    status: "Draft",
    created_at: "2026-07-25T08:00:00Z",
    updated_at: "2026-07-25T08:00:00Z",
  },
  {
    id: 7,
    judul: "Tugas Konsep Dasar Informatika",
    deskripsi:
      "Kerjakan latihan soal tentang konsep dasar informatika, algoritma, dan representasi data. Jawaban dikumpulkan dalam bentuk PDF.",
    kelas_mengajar_id: 1,
    guru_nama: "Asep Nugraha",
    mata_pelajaran: "Informatika",
    kelas: "X TKJ 1",
    lampiran: [
      { id: 7, nama: "latihan-konsep-informatika.pdf", ukuran: "720 KB", tipe: "application/pdf" },
    ],
    tanggal_dibuka: "2026-07-18",
    tenggat_waktu: "2026-07-24",
    tenggat_jam: "20:00",
    nilai_maksimal: 100,
    status: "Dipublikasikan",
    created_at: "2026-07-16T09:00:00Z",
    updated_at: "2026-07-18T08:00:00Z",
  },
  {
    id: 8,
    judul: "Latihan Subnetting IPv4",
    deskripsi:
      "Hitung dan gambarkan pembagian subnet untuk studi kasus yang diberikan. Sertakan langkah perhitungan VLSM.",
    kelas_mengajar_id: 2,
    guru_nama: "Asep Nugraha",
    mata_pelajaran: "Dasar Jaringan",
    kelas: "X TKJ 2",
    lampiran: [
      { id: 8, nama: "studi-kasus-subnetting.pdf", ukuran: "540 KB", tipe: "application/pdf" },
    ],
    tanggal_dibuka: "2026-07-19",
    tenggat_waktu: "2026-07-26",
    tenggat_jam: "23:59",
    nilai_maksimal: 100,
    status: "Dipublikasikan",
    created_at: "2026-07-17T08:30:00Z",
    updated_at: "2026-07-19T08:00:00Z",
  },
  {
    id: 9,
    judul: "Tugas Pemrograman Web: Validasi Formulir",
    deskripsi:
      "Buatlah formulir pendaftaran dengan validasi menggunakan JavaScript. Minimal 8 field input dengan pesan error yang jelas.",
    kelas_mengajar_id: 3,
    guru_nama: "Rina Wulandari",
    mata_pelajaran: "Pemrograman Web",
    kelas: "XI TKJ 1",
    lampiran: [
      { id: 9, nama: "template-validasi.zip", ukuran: "1.3 MB", tipe: "application/zip" },
    ],
    tanggal_dibuka: "2026-07-20",
    tenggat_waktu: "2026-08-05",
    tenggat_jam: "23:59",
    nilai_maksimal: 100,
    status: "Dipublikasikan",
    created_at: "2026-07-18T10:00:00Z",
    updated_at: "2026-07-20T08:00:00Z",
  },
  {
    id: 10,
    judul: "Tugas Sistem Operasi: Manajemen File Linux",
    deskripsi:
      "Praktikkan perintah manajemen file dan permission pada Linux (chmod, chown, find). Dokumentasikan hasilnya.",
    kelas_mengajar_id: 6,
    guru_nama: "Siti Rahayu",
    mata_pelajaran: "Sistem Operasi",
    kelas: "XI TKJ 1",
    lampiran: [
      { id: 10, nama: "panduan-manajemen-file.pdf", ukuran: "1.1 MB", tipe: "application/pdf" },
    ],
    tanggal_dibuka: "2026-07-22",
    tenggat_waktu: "2026-08-08",
    tenggat_jam: "23:59",
    nilai_maksimal: 100,
    status: "Dipublikasikan",
    created_at: "2026-07-20T09:00:00Z",
    updated_at: "2026-07-22T08:00:00Z",
  },
]
