import type { Materi } from "../types/materi"

export const DUMMY_MATERI: Materi[] = [
  {
    id: 1,
    judul: "Pengenalan Jaringan Komputer",
    deskripsi: "Materi pengantar tentang konsep dasar jaringan komputer, topologi, dan protokol.",
    kelas_mengajar_id: 2,
    guru_nama: "Asep Nugraha",
    mata_pelajaran: "Dasar Jaringan",
    kelas: "X TKJ 2",
    pertemuan: 1,
    jenis_materi: "PDF",
    thumbnail_url: null,
    lampiran: [
      { id: 1, nama: "slide-pengenalan-jaringan.pdf", ukuran: "2.4 MB", tipe: "application/pdf" },
      { id: 2, nama: "latihan-soal-1.pdf", ukuran: "540 KB", tipe: "application/pdf" },
    ],
    video_url: null,
    link_drive: null,
    link_eksternal: null,
    isi_materi: "<h2>Pengenalan Jaringan Komputer</h2><p>Jaringan komputer adalah sekumpulan komputer yang saling terhubung untuk berbagi data, sumber daya, dan layanan. Materi ini membahas konsep dasar jaringan termasuk topologi jaringan, jenis-jenis jaringan (LAN, WAN, MAN), serta protokum komunikasi dasar.</p><h3>Topik yang Dibahas</h3><ul><li>Definisi dan tujuan jaringan komputer</li><li>Jenis-jenis topologi jaringan</li><li>Perangkat jaringan</li><li>Protokum jaringan dasar</li></ul>",
    status: "Publish",
    created_at: "2026-07-02T08:00:00Z",
    updated_at: "2026-07-02T08:00:00Z",
  },
  {
    id: 2,
    judul: "Instalasi dan Konfigurasi MikroTik RouterOS",
    deskripsi: "Panduan langkah demi langkah instalasi dan konfigurasi awal MikroTik RouterOS.",
    kelas_mengajar_id: 3,
    guru_nama: "Rina Wulandari",
    mata_pelajaran: "Administrasi Sistem Jaringan",
    kelas: "XI TKJ 1",
    pertemuan: 1,
    jenis_materi: "Video",
    thumbnail_url: null,
    lampiran: [
      { id: 3, nama: "guide-mikrotik.pdf", ukuran: "5.1 MB", tipe: "application/pdf" },
    ],
    video_url: "https://www.youtube.com/watch?v=example1",
    link_drive: null,
    link_eksternal: "https://wiki.mikrotik.com/wiki/Manual:First_time_startup",
    isi_materi: "<h2>Instalasi MikroTik RouterOS</h2><p>RouterOS adalah sistem operasi routing yang berjalan pada perangkat keras MikroTik. Dalam materi ini, kita akan mempelajari cara menginstal dan melakukan konfigurasi awal pada perangkat MikroTik.</p><h3>Langkah Instalasi</h3><ol><li>Persiapan perangkat MikroTik</li><li>Instalasi RouterOS melalui Netinstall</li><li>Konfigurasi awal via WinBox</li><li>Pengaturan interface dan IP address</li></ol>",
    status: "Publish",
    created_at: "2026-07-03T09:15:00Z",
    updated_at: "2026-07-03T09:15:00Z",
  },
  {
    id: 3,
    judul: "HTML dan CSS Dasar",
    deskripsi: "Materi pengenalan HTML5 dan CSS3 untuk membuat halaman web pertama.",
    kelas_mengajar_id: 4,
    guru_nama: "Rina Wulandari",
    mata_pelajaran: "Pemrograman Web",
    kelas: "XI TBSM 1",
    pertemuan: 1,
    jenis_materi: "PPTX",
    thumbnail_url: null,
    lampiran: [
      { id: 4, nama: "belajar-html-css.pptx", ukuran: "3.2 MB", tipe: "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
      { id: 5, nama: "contoh-code.zip", ukuran: "120 KB", tipe: "application/zip" },
    ],
    video_url: null,
    link_drive: null,
    link_eksternal: null,
    isi_materi: "<h2>HTML dan CSS Dasar</h2><p>HTML (HyperText Markup Language) dan CSS (Cascading Style Sheets) adalah fondasi pembuatan halaman web. Materi ini mencakup struktur dokumen HTML, elemen-elemen penting, dan styling menggunakan CSS.</p><h3>Materi Pokok</h3><ul><li>Struktur dokumen HTML5</li><li>Elemen-elemen semantik</li><li>Formulir dan input</li><li>CSS Box Model</li><li>Layout dengan Flexbox</li></ul>",
    status: "Draft",
    created_at: "2026-07-05T10:00:00Z",
    updated_at: "2026-07-05T10:00:00Z",
  },
  {
    id: 4,
    judul: "Normalisasi Basis Data",
    deskripsi: "Penjelasan konsep normalisasi basis data dari 1NF hingga 3NF dengan contoh.",
    kelas_mengajar_id: 5,
    guru_nama: "Budi Santoso",
    mata_pelajaran: "Basis Data",
    kelas: "XII TKJ 1",
    pertemuan: 3,
    jenis_materi: "Video",
    thumbnail_url: null,
    lampiran: [],
    video_url: "https://www.youtube.com/watch?v=example2",
    link_drive: null,
    link_eksternal: null,
    isi_materi: "<h2>Normalisasi Basis Data</h2><p>Normalisasi adalah proses mengorganisasi kolom dan tabel pada basis data untuk meminimalkan redundansi data dan ketergantungan data. Materi ini membahas normalisasi dari 1NF hingga 3NF.</p><h3>Tahapan Normalisasi</h3><ul><li><strong>1NF:</strong> Eliminasi grup repetitif</li><li><strong>2NF:</strong> Eliminasi dependensi parsial</li><li><strong>3NF:</strong> Eliminasi dependensi transitif</li></ul>",
    status: "Publish",
    created_at: "2026-02-10T08:00:00Z",
    updated_at: "2026-03-15T14:30:00Z",
  },
  {
    id: 5,
    judul: "Pengenalan Sistem Operasi Linux",
    deskripsi: "Materi dasar tentang sistem operasi Linux, perintah dasar, dan administrasi file.",
    kelas_mengajar_id: 6,
    guru_nama: "Siti Rahayu",
    mata_pelajaran: "Sistem Operasi",
    kelas: "X TBSM 1",
    pertemuan: 2,
    jenis_materi: "PDF",
    thumbnail_url: null,
    lampiran: [
      { id: 6, nama: "linux-dasar.pdf", ukuran: "1.8 MB", tipe: "application/pdf" },
    ],
    video_url: null,
    link_drive: "https://drive.google.com/file/d/example-linux-dasar",
    link_eksternal: null,
    isi_materi: "<h2>Pengenalan Linux</h2><p>Linux adalah sistem operasi open-source berbasis Unix. Materi ini memberikan pengenalan mengenai arsitektur Linux, terminal/command line, dan administrasi file dasar.</p><h3>Topik Pembahasan</h3><ul><li>Sejarah dan filosofi Linux</li><li>Distribusi Linux populer</li><li>Perintah dasar terminal</li><li>Manajemen file dan direktori</li><li>Hak akses file (permissions)</li></ul>",
    status: "Publish",
    created_at: "2026-07-01T08:30:00Z",
    updated_at: "2026-07-01T08:30:00Z",
  },
  {
    id: 6,
    judul: "Konsep Dasar Informatika",
    deskripsi: "Pengenalan konsep dasar informatika meliputi data, informasi, dan teknologi.",
    kelas_mengajar_id: 1,
    guru_nama: "Asep Nugraha",
    mata_pelajaran: "Informatika",
    kelas: "X TKJ 1",
    pertemuan: 1,
    jenis_materi: "Lainnya",
    thumbnail_url: null,
    lampiran: [],
    video_url: null,
    link_drive: null,
    link_eksternal: null,
    isi_materi: "<h2>Konsep Dasar Informatika</h2><p>Informatika adalah ilmu yang mempelajari pengolahan data secara otomatis menggunakan komputer. Materi ini membahas perbedaan antara data dan informasi, serta peran teknologi dalam kehidupan sehari-hari.</p>",
    status: "Draft",
    created_at: "2026-07-06T11:00:00Z",
    updated_at: "2026-07-06T11:00:00Z",
  },
  {
    id: 7,
    judul: "Media Transmisi dan Topologi Jaringan",
    deskripsi: "Materi tentang jenis media transmisi (guided dan unguided) serta klasifikasi topologi jaringan.",
    kelas_mengajar_id: 2,
    guru_nama: "Asep Nugraha",
    mata_pelajaran: "Dasar Jaringan",
    kelas: "X TKJ 2",
    pertemuan: 2,
    jenis_materi: "PPTX",
    thumbnail_url: null,
    lampiran: [
      { id: 7, nama: "slide-media-transmisi.pptx", ukuran: "2.8 MB", tipe: "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
    ],
    video_url: null,
    link_drive: null,
    link_eksternal: null,
    isi_materi: "<h2>Media Transmisi dan Topologi Jaringan</h2><p>Media transmisi terbagi menjadi guided (kabel) dan unguided (nirkabel). Topologi jaringan menentukan bagaimana perangkat saling terhubung, seperti bus, star, ring, dan mesh.</p>",
    status: "Publish",
    created_at: "2026-07-15T08:30:00Z",
    updated_at: "2026-07-15T08:30:00Z",
  },
  {
    id: 8,
    judul: "Algoritma dan Logika Pemrograman",
    deskripsi: "Pengantar algoritma, flowchart, dan logika dasar pemrograman menggunakan pseudocode.",
    kelas_mengajar_id: 1,
    guru_nama: "Asep Nugraha",
    mata_pelajaran: "Informatika",
    kelas: "X TKJ 1",
    pertemuan: 2,
    jenis_materi: "DOCX",
    thumbnail_url: null,
    lampiran: [
      { id: 8, nama: "modul-algoritma.docx", ukuran: "1.9 MB", tipe: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
    ],
    video_url: null,
    link_drive: null,
    link_eksternal: null,
    isi_materi: "<h2>Algoritma dan Logika Pemrograman</h2><p>Algoritma adalah langkah-langkah sistematis untuk menyelesaikan masalah. Materi ini membahas penyajian algoritma melalui pseudocode dan flowchart.</p>",
    status: "Publish",
    created_at: "2026-07-17T09:15:00Z",
    updated_at: "2026-07-17T09:15:00Z",
  },
  {
    id: 9,
    judul: "CSS Flexbox dan Grid",
    deskripsi: "Materi lanjutan CSS untuk membangun layout responsif menggunakan Flexbox dan Grid.",
    kelas_mengajar_id: 3,
    guru_nama: "Rina Wulandari",
    mata_pelajaran: "Administrasi Sistem Jaringan",
    kelas: "XI TKJ 1",
    pertemuan: 2,
    jenis_materi: "URL",
    thumbnail_url: null,
    lampiran: [
      { id: 9, nama: "slide-flexbox-grid.pdf", ukuran: "3.2 MB", tipe: "application/pdf" },
    ],
    video_url: null,
    link_drive: null,
    link_eksternal: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout",
    isi_materi: "<h2>CSS Flexbox dan Grid</h2><p>Flexbox digunakan untuk layout satu dimensi, sedangkan Grid untuk dua dimensi. Materi ini membahas properti utama serta contoh penerapan pada halaman web.</p>",
    status: "Publish",
    created_at: "2026-07-20T10:00:00Z",
    updated_at: "2026-07-20T10:00:00Z",
  },
]
