import type { BankSoal } from "../types/bank-soal"

export const DUMMY_BANK_SOAL: BankSoal[] = [
  {
    id: 1,
    kode_soal: "PG-MTK-001",
    pertanyaan: "Hasil dari 3x² + 2x - 5 jika x = 2 adalah...",
    gambar_url: null,
    tipe_soal: "Pilihan Ganda",
    pilihan: { A: "11", B: "15", C: "19", D: "23", E: "27" },
    jawaban_benar: "C",
    mata_pelajaran: "Matematika",
    guru_nama: "Pak Ahmad Hidayat",
    kelas: "X RPL 1",
    kesulitan: "Mudah",
    status: "Aktif",
    created_at: "2025-07-01T08:00:00Z",
    updated_at: "2025-07-01T08:00:00Z",
  },
  {
    id: 2,
    kode_soal: "BS-FIS-002",
    pertanyaan: "Benda yang dilempar ke atas akan mengalami perlambatan karena pengaruh gravitasi.",
    gambar_url: null,
    tipe_soal: "Benar / Salah",
    pilihan: null,
    jawaban_benar: "Benar",
    mata_pelajaran: "Fisika",
    guru_nama: "Bu Dewi Lestari",
    kelas: "XI RPL 1",
    kesulitan: "Sedang",
    status: "Aktif",
    created_at: "2025-07-02T09:30:00Z",
    updated_at: "2025-07-02T09:30:00Z",
  },
  {
    id: 3,
    kode_soal: "IS-BIO-003",
    pertanyaan: "Sebutkan 3 organel sel yang berfungsi sebagai penghasil energi!",
    gambar_url: null,
    tipe_soal: "Isian Singkat",
    pilihan: null,
    jawaban_benar: "Mitokondria",
    mata_pelajaran: "Biologi",
    guru_nama: "Pak Budi Santoso",
    kelas: "XII RPL 1",
    kesulitan: "Sedang",
    status: "Draft",
    created_at: "2025-07-03T10:00:00Z",
    updated_at: "2025-07-03T10:00:00Z",
  },
  {
    id: 4,
    kode_soal: "ES-IPS-004",
    pertanyaan: "Jelaskan dampak globalisasi terhadap budaya lokal di Indonesia!",
    gambar_url: null,
    tipe_soal: "Essay",
    pilihan: null,
    jawaban_benar: "",
    mata_pelajaran: "Sosiologi",
    guru_nama: "Bu Siti Nurhaliza",
    kelas: "X RPL 2",
    kesulitan: "Sulit",
    status: "Draft",
    created_at: "2025-07-04T11:00:00Z",
    updated_at: "2025-07-04T11:00:00Z",
  },
  {
    id: 5,
    kode_soal: "PG-BIN-005",
    pertanyaan: "Sinonim dari kata 'rajin' adalah...",
    gambar_url: null,
    tipe_soal: "Pilihan Ganda",
    pilihan: { A: "malas", B: "giat", C: "lemah", D: "kuat", E: "cepat" },
    jawaban_benar: "B",
    mata_pelajaran: "Bahasa Indonesia",
    guru_nama: "Bu Siti Nurhaliza",
    kelas: "X RPL 1",
    kesulitan: "Mudah",
    status: "Aktif",
    created_at: "2025-07-05T08:00:00Z",
    updated_at: "2025-07-05T08:00:00Z",
  },
  {
    id: 6,
    kode_soal: "PG-KIM-006",
    pertanyaan: "Rumus kimia air adalah...",
    gambar_url: null,
    tipe_soal: "Pilihan Ganda",
    pilihan: { A: "H2O", B: "CO2", C: "NaCl", D: "O2", E: "H2" },
    jawaban_benar: "A",
    mata_pelajaran: "Kimia",
    guru_nama: "Pak Eko Prasetyo",
    kelas: "XI RPL 2",
    kesulitan: "Mudah",
    status: "Aktif",
    created_at: "2025-07-06T09:00:00Z",
    updated_at: "2025-07-06T09:00:00Z",
  },
  {
    id: 7,
    kode_soal: "BS-EKO-007",
    pertanyaan: "Inflasi selalu berdampak negatif terhadap perekonomian masyarakat.",
    gambar_url: null,
    tipe_soal: "Benar / Salah",
    pilihan: null,
    jawaban_benar: "Salah",
    mata_pelajaran: "Ekonomi",
    guru_nama: "Pak Ahmad Hidayat",
    kelas: "XII RPL 2",
    kesulitan: "Sedang",
    status: "Arsip",
    created_at: "2025-07-07T10:00:00Z",
    updated_at: "2025-07-07T10:00:00Z",
  },
  {
    id: 8,
    kode_soal: "PG-BIN-008",
    pertanyaan: "Antonim dari kata 'bersih' adalah...",
    gambar_url: null,
    tipe_soal: "Pilihan Ganda",
    pilihan: { A: "rapi", B: "suci", C: "kotor", D: "indah", E: "bersih" },
    jawaban_benar: "C",
    mata_pelajaran: "Bahasa Indonesia",
    guru_nama: "Bu Siti Nurhaliza",
    kelas: "XI RPL 1",
    kesulitan: "Mudah",
    status: "Aktif",
    created_at: "2025-07-08T11:00:00Z",
    updated_at: "2025-07-08T11:00:00Z",
  },
]
