import type { PengumpulanTugas } from "../types/pengumpulan"

export const DUMMY_PENGUMPULAN: PengumpulanTugas[] = [
  // Tugas 1: "Tugas Jaringan: Topologi dan Protokol" — X TKJ 2
  {
    id: 1,
    tugas_id: 1,
    siswa_id: 8,
    siswa_nama: "Budi Santoso",
    siswa_kelas: "X TKJ 2",
    file_jawaban: {
      nama: "jawaban-topologi-budi.pdf",
      ukuran: "1.1 MB",
      tipe: "application/pdf",
    },
    catatan: "Berikut adalah laporan tugas topologi jaringan yang sudah saya kerjakan.",
    waktu_pengumpulan: "2026-07-15T14:30:00Z",
    status: "Sudah Mengumpulkan",
    nilai: 85,
    created_at: "2026-07-15T14:30:00Z",
    updated_at: "2026-07-16T10:00:00Z",
  },

  // Tugas 2: "Praktikum MikroTik: Konfigurasi DHCP Server" — XI TKJ 1
  {
    id: 2,
    tugas_id: 2,
    siswa_id: 1,
    siswa_nama: "Rizki Pratama",
    siswa_kelas: "XI TKJ 1",
    file_jawaban: {
      nama: "laporan-dhcp-rizki.docx",
      ukuran: "2.3 MB",
      tipe: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    },
    catatan: "Laporan praktikum DHCP Server lengkap dengan screenshot konfigurasi.",
    waktu_pengumpulan: "2026-07-17T09:15:00Z",
    status: "Sudah Mengumpulkan",
    nilai: 90,
    created_at: "2026-07-17T09:15:00Z",
    updated_at: "2026-07-18T08:00:00Z",
  },
  {
    id: 3,
    tugas_id: 2,
    siswa_id: 4,
    siswa_nama: "Ahmad Rizky",
    siswa_kelas: "XI TKJ 1",
    file_jawaban: {
      nama: "praktikum-dhcp-ahmad.pdf",
      ukuran: "3.8 MB",
      tipe: "application/pdf",
    },
    catatan: "Telah melakukan konfigurasi DHCP pada MikroTik RB750.",
    waktu_pengumpulan: "2026-07-19T23:45:00Z",
    status: "Terlambat",
    nilai: 70,
    created_at: "2026-07-19T23:45:00Z",
    updated_at: "2026-07-20T08:00:00Z",
  },

  // Tugas 3: "Kuis HTML & CSS: Membuat Formulir" — XI TBSM 1
  {
    id: 4,
    tugas_id: 3,
    siswa_id: 2,
    siswa_nama: "Dewi Lestari",
    siswa_kelas: "XI TBSM 1",
    file_jawaban: {
      nama: "kuis-html-dewi.zip",
      ukuran: "850 KB",
      tipe: "application/zip",
    },
    catatan: "File zip berisi HTML, CSS, dan screenshot hasil.",
    waktu_pengumpulan: "2026-07-17T10:00:00Z",
    status: "Sudah Mengumpulkan",
    nilai: 95,
    created_at: "2026-07-17T10:00:00Z",
    updated_at: "2026-07-18T08:00:00Z",
  },
  {
    id: 5,
    tugas_id: 3,
    siswa_id: 5,
    siswa_nama: "Putri Wulandari",
    siswa_kelas: "XI TBSM 1",
    file_jawaban: null,
    catatan: "",
    waktu_pengumpulan: null,
    status: "Belum Mengumpulkan",
    nilai: null,
    created_at: "2026-07-15T08:00:00Z",
    updated_at: "2026-07-15T08:00:00Z",
  },

  // Tugas 4: "Tugas Basis Data: ERD Perpustakaan" — XII TKJ 1 (Ditutup)
  {
    id: 6,
    tugas_id: 4,
    siswa_id: 3,
    siswa_nama: "Fajar Nugroho",
    siswa_kelas: "XII TKJ 1",
    file_jawaban: {
      nama: "erd-perpustakaan-fajar.pdf",
      ukuran: "2.1 MB",
      tipe: "application/pdf",
    },
    catatan: "ERD menggunakan notasi Chen, 6 entitas.",
    waktu_pengumpulan: "2026-02-25T16:00:00Z",
    status: "Sudah Mengumpulkan",
    nilai: 88,
    created_at: "2026-02-25T16:00:00Z",
    updated_at: "2026-02-26T08:00:00Z",
  },

  // Tugas 5: "Tugas Linux: Perintah Dasar Terminal" — X TBSM 1 (Ditutup)
  {
    id: 7,
    tugas_id: 5,
    siswa_id: 2,
    siswa_nama: "Dewi Lestari",
    siswa_kelas: "X TBSM 1",
    file_jawaban: {
      nama: "latihan-linux-dewi.pdf",
      ukuran: "1.8 MB",
      tipe: "application/pdf",
    },
    catatan: "Screenshot setiap perintah beserta output.",
    waktu_pengumpulan: "2026-07-10T08:30:00Z",
    status: "Sudah Mengumpulkan",
    nilai: 80,
    created_at: "2026-07-10T08:30:00Z",
    updated_at: "2026-07-11T08:00:00Z",
  },

  // Tugas 6: "Proyek Akhir: Website Portfolio" — XI TBSM 1 (Draft)
  {
    id: 8,
    tugas_id: 6,
    siswa_id: 2,
    siswa_nama: "Dewi Lestari",
    siswa_kelas: "XI TBSM 1",
    file_jawaban: null,
    catatan: "",
    waktu_pengumpulan: null,
    status: "Belum Mengumpulkan",
    nilai: null,
    created_at: "2026-07-25T08:00:00Z",
    updated_at: "2026-07-25T08:00:00Z",
  },
  {
    id: 9,
    tugas_id: 6,
    siswa_id: 5,
    siswa_nama: "Putri Wulandari",
    siswa_kelas: "XI TBSM 1",
    file_jawaban: null,
    catatan: "",
    waktu_pengumpulan: null,
    status: "Belum Mengumpulkan",
    nilai: null,
    created_at: "2026-07-25T08:00:00Z",
    updated_at: "2026-07-25T08:00:00Z",
  },
  {
    id: 10,
    tugas_id: 1,
    siswa_id: 9,
    siswa_nama: "Ahmad Fauzi",
    siswa_kelas: "X TKJ 2",
    file_jawaban: {
      nama: "laporan-topologi-andi.pdf",
      ukuran: "1.4 MB",
      tipe: "application/pdf",
    },
    catatan: "Laporan lengkap beserta diagram setiap topologi.",
    waktu_pengumpulan: "2026-07-20T10:00:00Z",
    status: "Sudah Mengumpulkan",
    nilai: null,
    created_at: "2026-07-20T10:00:00Z",
    updated_at: "2026-07-20T10:00:00Z",
  },
  {
    id: 11,
    tugas_id: 7,
    siswa_id: 10,
    siswa_nama: "Citra Ayu",
    siswa_kelas: "X TKJ 1",
    file_jawaban: {
      nama: "latihan-konsep-dian.pdf",
      ukuran: "860 KB",
      tipe: "application/pdf",
    },
    catatan: "Sudah mengerjakan semua soal latihan.",
    waktu_pengumpulan: "2026-07-21T09:30:00Z",
    status: "Sudah Mengumpulkan",
    nilai: null,
    created_at: "2026-07-21T09:30:00Z",
    updated_at: "2026-07-21T09:30:00Z",
  },
  {
    id: 12,
    tugas_id: 8,
    siswa_id: 11,
    siswa_nama: "Eko Prasetyo",
    siswa_kelas: "X TKJ 2",
    file_jawaban: {
      nama: "subnetting-candra.pdf",
      ukuran: "1.2 MB",
      tipe: "application/pdf",
    },
    catatan: "Perhitungan VLSM disertai langkah lengkap.",
    waktu_pengumpulan: "2026-07-22T14:00:00Z",
    status: "Sudah Mengumpulkan",
    nilai: null,
    created_at: "2026-07-22T14:00:00Z",
    updated_at: "2026-07-22T14:00:00Z",
  },
  {
    id: 13,
    tugas_id: 9,
    siswa_id: 1,
    siswa_nama: "Rizki Pratama",
    siswa_kelas: "XI TKJ 1",
    file_jawaban: {
      nama: "validasi-form-rizki.zip",
      ukuran: "1.1 MB",
      tipe: "application/zip",
    },
    catatan: "Semua field tervalidasi dan berisi pesan error.",
    waktu_pengumpulan: "2026-07-25T08:00:00Z",
    status: "Sudah Mengumpulkan",
    nilai: 85,
    created_at: "2026-07-25T08:00:00Z",
    updated_at: "2026-07-26T09:00:00Z",
  },
  {
    id: 14,
    tugas_id: 10,
    siswa_id: 1,
    siswa_nama: "Rizki Pratama",
    siswa_kelas: "XI TKJ 1",
    file_jawaban: null,
    catatan: "",
    waktu_pengumpulan: null,
    status: "Belum Mengumpulkan",
    nilai: null,
    created_at: "2026-07-22T08:00:00Z",
    updated_at: "2026-07-22T08:00:00Z",
  },
]
