import type { PaketSoal } from "../types/paket-soal"

export const DUMMY_PAKET_SOAL: PaketSoal[] = [
  {
    id: 1,
    nama_paket: "UTS Matematika Semester Ganjil",
    deskripsi: "Paket soal Ulangan Tengah Semester untuk mata pelajaran Matematika kelas X RPL.",
    mata_pelajaran: "Matematika",
    guru_nama: "Pak Ahmad Hidayat",
    durasi: 90,
    nilai_maksimal: 100,
    soal_ids: [1],
    status: "Aktif",
    created_at: "2025-07-01T08:00:00Z",
    updated_at: "2025-07-01T08:00:00Z",
  },
  {
    id: 2,
    nama_paket: "Quiz Bahasa Indonesia - Sinonim & Antonim",
    deskripsi: "Paket quiz singkat untuk menguasai kosakata sinonim dan antonim.",
    mata_pelajaran: "Bahasa Indonesia",
    guru_nama: "Bu Siti Nurhaliza",
    durasi: 30,
    nilai_maksimal: 100,
    soal_ids: [5, 8],
    status: "Aktif",
    created_at: "2025-07-02T09:00:00Z",
    updated_at: "2025-07-02T09:00:00Z",
  },
  {
    id: 3,
    nama_paket: "Try Out Fisika - Mekanika",
    deskripsi: "Simulasi try out untuk persiapan ujian nasional mata pelajaran Fisika.",
    mata_pelajaran: "Fisika",
    guru_nama: "Bu Dewi Lestari",
    durasi: 120,
    nilai_maksimal: 100,
    soal_ids: [2],
    status: "Draft",
    created_at: "2025-07-03T10:00:00Z",
    updated_at: "2025-07-03T10:00:00Z",
  },
  {
    id: 4,
    nama_paket: "PTS Kimia Semester Ganjil",
    deskripsi: "Paket soal Penilaian Tengah Semester untuk mata pelajaran Kimia.",
    mata_pelajaran: "Kimia",
    guru_nama: "Pak Eko Prasetyo",
    durasi: 60,
    nilai_maksimal: 100,
    soal_ids: [6],
    status: "Draft",
    created_at: "2025-07-04T11:00:00Z",
    updated_at: "2025-07-04T11:00:00Z",
  },
  {
    id: 5,
    nama_paket: "Ulangan Harian Biologi - Sel",
    deskripsi: "Ulangan harian tentang struktur dan fungsi sel.",
    mata_pelajaran: "Biologi",
    guru_nama: "Pak Budi Santoso",
    durasi: 45,
    nilai_maksimal: 100,
    soal_ids: [3],
    status: "Arsip",
    created_at: "2025-07-05T08:00:00Z",
    updated_at: "2025-07-05T08:00:00Z",
  },
]
