<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    private const STUDENTS = [
        [
            'foto' => null,
            'nis' => '2024001',
            'nisn' => '0081234001',
            'nama_lengkap' => 'Rizki Pratama',
            'jenis_kelamin' => 'Laki-laki',
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '2008-05-15',
            'agama' => 'Islam',
            'alamat' => 'Jl. Sudirman No. 5, Jakarta Pusat',
            'kelas' => 'XI TKJ 1',
            'tahun_masuk' => '2023',
            'tahun_ajaran' => '2025/2026',
            'status' => 'Aktif',
            'nama_ayah' => 'Budi Pratama',
            'nama_ibu' => 'Siti Pratama',
            'no_hp_ortu' => '081234560001',
            'alamat_ortu' => 'Jl. Sudirman No. 5, Jakarta Pusat',
        ],
        [
            'foto' => null,
            'nis' => '2024002',
            'nisn' => '0081234002',
            'nama_lengkap' => 'Dewi Lestari',
            'jenis_kelamin' => 'Perempuan',
            'tempat_lahir' => 'Bandung',
            'tanggal_lahir' => '2008-08-20',
            'agama' => 'Islam',
            'alamat' => 'Jl. Asia Afrika No. 12, Bandung',
            'kelas' => 'XI TBSM 1',
            'tahun_masuk' => '2023',
            'tahun_ajaran' => '2025/2026',
            'status' => 'Aktif',
            'nama_ayah' => 'Ahmad Lestari',
            'nama_ibu' => 'Rina Lestari',
            'no_hp_ortu' => '081234560002',
            'alamat_ortu' => 'Jl. Asia Afrika No. 12, Bandung',
        ],
        [
            'foto' => null,
            'nis' => '2022003',
            'nisn' => '0081234003',
            'nama_lengkap' => 'Fajar Nugroho',
            'jenis_kelamin' => 'Laki-laki',
            'tempat_lahir' => 'Surabaya',
            'tanggal_lahir' => '2006-03-10',
            'agama' => 'Kristen',
            'alamat' => 'Jl. Pemuda No. 88, Surabaya',
            'kelas' => 'XII TKJ 2',
            'tahun_masuk' => '2022',
            'tahun_ajaran' => '2024/2025',
            'status' => 'Alumni',
            'nama_ayah' => 'Dwi Nugroho',
            'nama_ibu' => 'Lina Nugroho',
            'no_hp_ortu' => '081234560003',
            'alamat_ortu' => 'Jl. Pemuda No. 88, Surabaya',
        ],
        [
            'foto' => null,
            'nis' => '2023004',
            'nisn' => '0081234004',
            'nama_lengkap' => 'Ahmad Rizky',
            'jenis_kelamin' => 'Laki-laki',
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '2007-11-25',
            'agama' => 'Islam',
            'alamat' => 'Jl. Gatot Subroto No. 20, Jakarta Selatan',
            'kelas' => 'XI TKJ 1',
            'tahun_masuk' => '2023',
            'tahun_ajaran' => '2025/2026',
            'status' => 'Pindah',
            'nama_ayah' => 'Hendra Rizky',
            'nama_ibu' => 'Maya Rizky',
            'no_hp_ortu' => '081234560004',
            'alamat_ortu' => 'Jl. Gatot Subroto No. 20, Jakarta Selatan',
        ],
        [
            'foto' => null,
            'nis' => '2023005',
            'nisn' => '0081234005',
            'nama_lengkap' => 'Putri Wulandari',
            'jenis_kelamin' => 'Perempuan',
            'tempat_lahir' => 'Yogyakarta',
            'tanggal_lahir' => '2008-01-30',
            'agama' => 'Islam',
            'alamat' => 'Jl. Malioboro No. 5, Yogyakarta',
            'kelas' => 'XI TBSM 1',
            'tahun_masuk' => '2023',
            'tahun_ajaran' => '2025/2026',
            'status' => 'Aktif',
            'nama_ayah' => 'Sugeng Wulandari',
            'nama_ibu' => 'Dewi Wulandari',
            'no_hp_ortu' => '081234560005',
            'alamat_ortu' => 'Jl. Malioboro No. 5, Yogyakarta',
        ],
        [
            'foto' => null,
            'nis' => '2022006',
            'nisn' => '0081234006',
            'nama_lengkap' => 'Andi Saputra',
            'jenis_kelamin' => 'Laki-laki',
            'tempat_lahir' => 'Semarang',
            'tanggal_lahir' => '2006-07-12',
            'agama' => 'Islam',
            'alamat' => 'Jl. Pandanaran No. 15, Semarang',
            'kelas' => 'XII BDP 1',
            'tahun_masuk' => '2022',
            'tahun_ajaran' => '2024/2025',
            'status' => 'Alumni',
            'nama_ayah' => 'Slamet Saputra',
            'nama_ibu' => 'Endang Saputra',
            'no_hp_ortu' => '081234560006',
            'alamat_ortu' => 'Jl. Pandanaran No. 15, Semarang',
        ],
        [
            'foto' => null,
            'nis' => '2023007',
            'nisn' => '0081234007',
            'nama_lengkap' => 'Sari Permata',
            'jenis_kelamin' => 'Perempuan',
            'tempat_lahir' => 'Yogyakarta',
            'tanggal_lahir' => '2007-09-05',
            'agama' => 'Hindu',
            'alamat' => 'Jl. Malioboro No. 30, Yogyakarta',
            'kelas' => 'XI BDP 2',
            'tahun_masuk' => '2023',
            'tahun_ajaran' => '2025/2026',
            'status' => 'Keluar',
            'nama_ayah' => 'Ketut Permata',
            'nama_ibu' => 'Wayan Permata',
            'no_hp_ortu' => '081234560007',
            'alamat_ortu' => 'Jl. Malioboro No. 30, Yogyakarta',
        ],
        [
            'foto' => null,
            'nis' => '2024008',
            'nisn' => '0081234008',
            'nama_lengkap' => 'Budi Santoso',
            'jenis_kelamin' => 'Laki-laki',
            'tempat_lahir' => 'Surabaya',
            'tanggal_lahir' => '2008-02-14',
            'agama' => 'Kristen',
            'alamat' => 'Jl. Dinoyo No. 42, Surabaya',
            'kelas' => 'X TKJ 2',
            'tahun_masuk' => '2024',
            'tahun_ajaran' => '2025/2026',
            'status' => 'Aktif',
            'nama_ayah' => 'Hendra Santoso',
            'nama_ibu' => 'Rina Santoso',
            'no_hp_ortu' => '081234560008',
            'alamat_ortu' => 'Jl. Dinoyo No. 42, Surabaya',
        ],
    ];

    public function run(): void
    {
        foreach (self::STUDENTS as $data) {
            Student::updateOrCreate(
                ['nis' => $data['nis']],
                $data
            );
        }
    }
}
