import type { Notifikasi } from "@/features/notifications/types/notifikasi"

export const DUMMY_NOTIFIKASI: Notifikasi[] = [
  {
    id: 6,
    tipe: "penilaian",
    judul: "Tugas kamu sudah dinilai",
    pesan: "Tugas 'Membuat Diagram Jaringan' telah dinilai oleh Bu Rina.",
    href: "/siswa/kelas/3",
    target_roles: ["siswa"],
    is_read: false,
    created_at: "2026-08-02T08:15:00.000Z",
  },
  {
    id: 5,
    tipe: "materi",
    judul: "Materi Baru: Pengenalan Jaringan Komputer",
    pesan: "Bapak Asep Nugraha menambahkan materi baru di kelas Informatika — X TKJ 1.",
    href: "/siswa/kelas/1",
    target_roles: ["siswa"],
    is_read: false,
    created_at: "2026-08-01T02:30:00.000Z",
  },
  {
    id: 4,
    tipe: "pengumuman",
    judul: "Pembagian Rapor Semester Ganjil",
    pesan: "Pengumuman baru dipublikasikan untuk seluruh siswa.",
    href: "/siswa/pengumuman/25",
    target_roles: ["siswa"],
    is_read: false,
    created_at: "2026-07-31T04:00:00.000Z",
  },
  {
    id: 3,
    tipe: "tugas",
    judul: "Tugas Baru: Membuat Topologi Jaringan",
    pesan: "Tugas baru dipublikasikan di kelas Dasar Jaringan — X TKJ 2. Tenggat: 12 Agustus 2026.",
    href: "/guru/kelas/2",
    target_roles: ["guru"],
    is_read: false,
    created_at: "2026-07-30T07:45:00.000Z",
  },
  {
    id: 2,
    tipe: "penilaian",
    judul: "Penilaian menunggu aksi",
    pesan: "Ada 3 tugas yang menunggu penilaian di kelas Anda.",
    href: "/guru/kelas/1",
    target_roles: ["guru"],
    is_read: false,
    created_at: "2026-07-29T01:20:00.000Z",
  },
  {
    id: 1,
    tipe: "sistem",
    judul: "Selamat datang di SIAPOS",
    pesan: "Aplikasi penilaian dan pembelajaran SIAPOS siap digunakan.",
    target_roles: ["super_admin", "admin", "guru", "siswa", "wali"],
    is_read: true,
    created_at: "2026-07-28T00:00:00.000Z",
  },
]
