import type { Penilaian } from "../types/penilaian"

export const DUMMY_PENILAIAN: Penilaian[] = [
  // Tugas 1: "Tugas Jaringan: Topologi dan Protokol" — X TKJ 2
  {
    id: 1,
    pengumpulan_id: 1,
    tugas_id: 1,
    siswa_nama: "Budi Santoso",
    siswa_kelas: "X TKJ 2",
    mata_pelajaran: "Dasar Jaringan",
    guru_nama: "Asep Nugraha",
    tugas_judul: "Tugas Jaringan: Topologi dan Protokol",
    tenggat_waktu: "2026-07-17",
    nilai: 85,
    feedback_guru:
      "Laporan lengkap dan sistematis. Penjelasan topologi jaringan sudah baik, namun bisa ditambahkan diagram untuk setiap topologi.",
    status_penilaian: "Sudah Dinilai",
    created_at: "2026-07-15T14:30:00Z",
    updated_at: "2026-07-16T10:00:00Z",
  },

  // Tugas 2: "Praktikum MikroTik: Konfigurasi DHCP Server" — XI TKJ 1
  {
    id: 2,
    pengumpulan_id: 2,
    tugas_id: 2,
    siswa_nama: "Rizki Pratama",
    siswa_kelas: "XI TKJ 1",
    mata_pelajaran: "Administrasi Sistem Jaringan",
    guru_nama: "Rina Wulandari",
    tugas_judul: "Praktikum MikroTik: Konfigurasi DHCP Server",
    tenggat_waktu: "2026-07-19",
    nilai: 90,
    feedback_guru:
      "Praktikum sangat baik. Dokumentasi langkah konfigurasi lengkap dengan screenshot. Pengujian DHCP berhasil.",
    status_penilaian: "Sudah Dinilai",
    created_at: "2026-07-17T09:15:00Z",
    updated_at: "2026-07-18T08:00:00Z",
  },
  {
    id: 3,
    pengumpulan_id: 3,
    tugas_id: 2,
    siswa_nama: "Ahmad Rizky",
    siswa_kelas: "XI TKJ 1",
    mata_pelajaran: "Administrasi Sistem Jaringan",
    guru_nama: "Rina Wulandari",
    tugas_judul: "Praktikum MikroTik: Konfigurasi DHCP Server",
    tenggat_waktu: "2026-07-19",
    nilai: 70,
    feedback_guru:
      "Konfigurasi DHCP sudah benar namun dokumentasi kurang lengkap. Pengumpulan terlambat 1 hari.",
    status_penilaian: "Sudah Dinilai",
    created_at: "2026-07-19T23:45:00Z",
    updated_at: "2026-07-20T08:00:00Z",
  },

  // Tugas 3: "Kuis HTML & CSS: Membuat Formulir" — XI TBSM 1
  {
    id: 4,
    pengumpulan_id: 4,
    tugas_id: 3,
    siswa_nama: "Dewi Lestari",
    siswa_kelas: "XI TBSM 1",
    mata_pelajaran: "Pemrograman Web",
    guru_nama: "Rina Wulandari",
    tugas_judul: "Kuis HTML & CSS: Membuat Formulir",
    tenggat_waktu: "2026-07-18",
    nilai: 95,
    feedback_guru:
      "Formulir dibuat dengan 8 field input, styling CSS sangat rapi. Screenshot hasil juga jelas.",
    status_penilaian: "Sudah Dinilai",
    created_at: "2026-07-17T10:00:00Z",
    updated_at: "2026-07-18T08:00:00Z",
  },
  {
    id: 5,
    pengumpulan_id: 5,
    tugas_id: 3,
    siswa_nama: "Putri Wulandari",
    siswa_kelas: "XI TBSM 1",
    mata_pelajaran: "Pemrograman Web",
    guru_nama: "Rina Wulandari",
    tugas_judul: "Kuis HTML & CSS: Membuat Formulir",
    tenggat_waktu: "2026-07-18",
    nilai: null,
    feedback_guru: "",
    status_penilaian: "Belum Dinilai",
    created_at: "2026-07-15T08:00:00Z",
    updated_at: "2026-07-15T08:00:00Z",
  },

  // Tugas 4: "Tugas Basis Data: ERD Perpustakaan" — XII TKJ 1
  {
    id: 6,
    pengumpulan_id: 6,
    tugas_id: 4,
    siswa_nama: "Fajar Nugroho",
    siswa_kelas: "XII TKJ 1",
    mata_pelajaran: "Basis Data",
    guru_nama: "Budi Santoso",
    tugas_judul: "Tugas Basis Data: ERD Perpustakaan",
    tenggat_waktu: "2026-02-27",
    nilai: 88,
    feedback_guru:
      "ERD menggunakan notasi Chen sudah benar. 6 entitas sudah memenuhi syarat minimum. Relasi antar entitas jelas.",
    status_penilaian: "Sudah Dinilai",
    created_at: "2026-02-25T16:00:00Z",
    updated_at: "2026-02-26T08:00:00Z",
  },

  // Tugas 5: "Tugas Linux: Perintah Dasar Terminal" — X TBSM 1
  {
    id: 7,
    pengumpulan_id: 7,
    tugas_id: 5,
    siswa_nama: "Dewi Lestari",
    siswa_kelas: "X TBSM 1",
    mata_pelajaran: "Sistem Operasi",
    guru_nama: "Siti Rahayu",
    tugas_judul: "Tugas Linux: Perintah Dasar Terminal",
    tenggat_waktu: "2026-07-12",
    nilai: 80,
    feedback_guru:
      "Screenshot perintah dan output sudah lengkap. Beberapa perintah bisa ditambahkan penjelasan.",
    status_penilaian: "Sudah Dinilai",
    created_at: "2026-07-10T08:30:00Z",
    updated_at: "2026-07-11T08:00:00Z",
  },

  // Tugas 6: "Proyek Akhir: Website Portfolio" — XI TBSM 1 (Draft)
  {
    id: 8,
    pengumpulan_id: 8,
    tugas_id: 6,
    siswa_nama: "Dewi Lestari",
    siswa_kelas: "XI TBSM 1",
    mata_pelajaran: "Pemrograman Web",
    guru_nama: "Rina Wulandari",
    tugas_judul: "Proyek Akhir: Website Portfolio",
    tenggat_waktu: "2026-08-31",
    nilai: null,
    feedback_guru: "",
    status_penilaian: "Belum Dinilai",
    created_at: "2026-07-25T08:00:00Z",
    updated_at: "2026-07-25T08:00:00Z",
  },
  {
    id: 9,
    pengumpulan_id: 9,
    tugas_id: 6,
    siswa_nama: "Putri Wulandari",
    siswa_kelas: "XI TBSM 1",
    mata_pelajaran: "Pemrograman Web",
    guru_nama: "Rina Wulandari",
    tugas_judul: "Proyek Akhir: Website Portfolio",
    tenggat_waktu: "2026-08-31",
    nilai: null,
    feedback_guru: "",
    status_penilaian: "Belum Dinilai",
    created_at: "2026-07-25T08:00:00Z",
    updated_at: "2026-07-25T08:00:00Z",
  },
]
