import type { Pengumuman } from "../types/pengumuman"

export const DUMMY_PENGUMUMAN: Pengumuman[] = [
  {
    id: 1,
    judul: "Jadwal UAS Semester Ganjil 2026/2027",
    ringkasan: "Pengumuman jadwal pelaksanaan Ujian Akhir Semester Ganjil tahun ajaran 2026/2027",
    isi: "Diberitahukan kepada seluruh siswa bahwa Ujian Akhir Semester Ganjil tahun ajaran 2026/2027 akan dilaksanakan pada tanggal 30 November - 4 Desember 2026. Persiapan dan jadwal lengkap dapat dilihat di papan pengumuman atau menghubungi wali kelas masing-masing.",
    kategori: "Akademik",
    target: "Semua Pengguna",
    status: "Dipublikasikan",
    penulis: "Admin Sekolah",
    pinned: true,
    lampiran: [
      { id: 1, nama: "jadwal-uas-ganjil-2026-2027.pdf", ukuran: "245 KB", tipe: "application/pdf" },
      { id: 2, nama: "kisi-kisi-uas.docx", ukuran: "1.2 MB", tipe: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
    ],
    tanggal_publish: "2026-11-01",
    created_at: "2026-11-01T08:00:00Z",
    updated_at: "2026-11-01T08:00:00Z",
  },
  {
    id: 2,
    judul: "Libur Akhir Tahun 2026",
    ringkasan: "Informasi libur akhir tahun menjelang tahun ajaran baru",
    isi: "Libur akhir tahun akan dimulai pada tanggal 19 Desember 2026 sampai dengan 3 Januari 2027. Kegiatan belajar mengajar akan dimulai kembali pada tanggal 4 Januari 2027. Selamat berlibur!",
    kategori: "Libur",
    target: "Semua Pengguna",
    status: "Dipublikasikan",
    penulis: "Admin Sekolah",
    pinned: true,
    lampiran: [],
    tanggal_publish: "2026-12-10",
    created_at: "2026-12-10T09:00:00Z",
    updated_at: "2026-12-10T09:00:00Z",
  },
  {
    id: 3,
    judul: "Pelaksanaan PKL Kelas XII TKJ",
    ringkasan: "Informasi PKL untuk siswa kelas XII jurusan TKJ",
    isi: "Praktek Kerja Lapangan untuk siswa kelas XII TKJ akan dilaksanakan pada bulan April - Mei 2026. Siswa diwajibkan mengikuti pembekalan PKL yang akan diadakan pada tanggal 25 Maret 2026.",
    kategori: "PKL",
    target: "TKJ",
    status: "Dipublikasikan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [
      { id: 1, nama: "buku-panduan-pkl.pdf", ukuran: "3.5 MB", tipe: "application/pdf" },
    ],
    tanggal_publish: "2026-03-01",
    created_at: "2026-03-01T10:00:00Z",
    updated_at: "2026-03-01T10:00:00Z",
  },
  {
    id: 4,
    judul: "Pengumuman Hasil UTS Ganjil 2026/2027",
    ringkasan: "Hasil UTS sudah dapat dilihat oleh siswa",
    isi: "Hasil Ujian Tengah Semester Ganjil tahun ajaran 2026/2027 sudah dapat diakses melalui sistem. Silakan login ke akun masing-masing untuk melihat nilai.",
    kategori: "Assessment",
    target: "Siswa",
    status: "Dipublikasikan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-09-30",
    created_at: "2026-09-30T11:00:00Z",
    updated_at: "2026-09-30T11:00:00Z",
  },
  {
    id: 5,
    judul: "Perubahan Jadwal Pelajaran Kelas X",
    ringkasan: "Penyesuaian jadwal pelajaran untuk kelas X",
    isi: "Sehubungan dengan perubahan alokasi guru, jadwal pelajaran untuk kelas X mengalami perubahan. Silakan cek jadwal terbaru di menu Jadwal Pelajaran.",
    kategori: "Pembelajaran",
    target: "Kelas Tertentu",
    kelas: "X TKJ 1",
    status: "Dipublikasikan",
    penulis: "Waka Kurikulum",
    pinned: false,
    lampiran: [
      { id: 1, nama: "jadwal-baru-kelas-x.png", ukuran: "890 KB", tipe: "image/png" },
    ],
    tanggal_publish: "2026-08-15",
    created_at: "2026-08-15T07:30:00Z",
    updated_at: "2026-08-15T07:30:00Z",
  },
  {
    id: 6,
    judul: "Kegiatan Pramuka Jambore Sekolah",
    ringkasan: "Jambore pramuka tingkat sekolah akan dilaksanakan",
    isi: "Kegiatan Jambore Pramuka akan dilaksanakan pada tanggal 5-7 Oktober 2026 di Bumi Perkemahan. Seluruh anggota pramuka wajib mengikuti kegiatan ini.",
    kategori: "Kegiatan Sekolah",
    target: "Siswa",
    status: "Dipublikasikan",
    penulis: "Admin Sekolah",
    pinned: true,
    lampiran: [],
    tanggal_publish: "2026-09-20",
    created_at: "2026-09-20T08:00:00Z",
    updated_at: "2026-09-20T08:00:00Z",
  },
  {
    id: 7,
    judul: "Daftar Ulang Siswa Baru",
    ringkasan: "Informasi daftar ulang untuk siswa baru",
    isi: "Daftar ulang siswa baru tahun ajaran 2026/2027 dilaksanakan pada tanggal 1-10 Juli 2026. Silakan datang ke bagian administrasi dengan membawa persyaratan yang sudah ditentukan.",
    kategori: "Informasi Umum",
    target: "Semua Pengguna",
    status: "Dipublikasikan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [
      { id: 1, nama: "persyaratan-daftar-ulang.pdf", ukuran: "180 KB", tipe: "application/pdf" },
    ],
    tanggal_publish: "2026-06-15",
    created_at: "2026-06-15T09:00:00Z",
    updated_at: "2026-06-15T09:00:00Z",
  },
  {
    id: 8,
    judul: "Workshop Implementasi Kurikulum Merdeka",
    ringkasan: "Workshop untuk guru mengenai Kurikulum Merdeka",
    isi: "Workshop Implementasi Kurikulum Merdeka akan dilaksanakan pada tanggal 28-29 Desember 2026. Seluruh guru diwajibkan mengikuti kegiatan ini.",
    kategori: "Pembelajaran",
    target: "Guru",
    status: "Draft",
    penulis: "Asep Nugraha",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-12-28",
    created_at: "2026-12-20T10:00:00Z",
    updated_at: "2026-12-20T10:00:00Z",
  },
  {
    id: 9,
    judul: "Rapat Koordinasi Guru Akhir Semester",
    ringkasan: "Rapat guru membahas evaluasi semester",
    isi: "Rapat koordinasi guru akhir semester akan dilaksanakan pada tanggal 21 Desember 2026. Agenda rapat meliputi evaluasi pembelajaran dan persiapan semester baru.",
    kategori: "Akademik",
    target: "Guru",
    status: "Dipublikasikan",
    penulis: "Kepala Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-12-15",
    created_at: "2026-12-15T08:00:00Z",
    updated_at: "2026-12-15T08:00:00Z",
  },
  {
    id: 10,
    judul: "Peringatan Maulid Nabi Muhammad SAW",
    ringkasan: "Kegiatan peringatan Maulid Nabi",
    isi: "Peringatan Maulid Nabi Muhammad SAW 1448 H akan dilaksanakan pada tanggal 4 September 2026. Acara akan dimulai pukul 07.30 di lapangan sekolah.",
    kategori: "Kegiatan Sekolah",
    target: "Semua Pengguna",
    status: "Dipublikasikan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-08-20",
    created_at: "2026-08-20T09:00:00Z",
    updated_at: "2026-08-20T09:00:00Z",
  },
  {
    id: 11,
    judul: "Pengumuman Kelulusan Kelas XII",
    ringkasan: "Pengumuman kelulusan siswa kelas XII",
    isi: "Pengumuman kelulusan siswa kelas XII akan disampaikan pada tanggal 20 Juni 2026. Informasi lebih lanjut akan disampaikan melalui wali kelas masing-masing.",
    kategori: "Akademik",
    target: "Siswa",
    status: "Diarsipkan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-06-10",
    created_at: "2026-06-10T08:00:00Z",
    updated_at: "2026-06-10T08:00:00Z",
  },
  {
    id: 12,
    judul: "Pendaftaran Lomba Peringatan HUT RI",
    ringkasan: "Lomba dalam rangka HUT RI ke-81",
    isi: "Dalam rangka memperingati HUT RI ke-81, sekolah akan mengadakan berbagai lomba. Pendaftaran dibuka sampai 10 Agustus 2026. Ayo ikuti dan tunjukkan bakatmu!",
    kategori: "Kegiatan Sekolah",
    target: "Siswa",
    status: "Dipublikasikan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [
      { id: 1, nama: "poster-lomba-hut-ri.jpg", ukuran: "2.1 MB", tipe: "image/jpeg" },
    ],
    tanggal_publish: "2026-07-20",
    created_at: "2026-07-20T10:00:00Z",
    updated_at: "2026-07-20T10:00:00Z",
  },
  {
    id: 13,
    judul: "Jadwal Pembekalan PKL TBSM",
    ringkasan: "Pembekalan PKL untuk siswa TBSM",
    isi: "Pembekalan PKL untuk siswa kelas XI TBSM akan dilaksanakan pada tanggal 25 Juli 2026. Kehadiran wajib bagi seluruh siswa yang akan melaksanakan PKL.",
    kategori: "PKL",
    target: "TBSM",
    status: "Dipublikasikan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-07-10",
    created_at: "2026-07-10T08:30:00Z",
    updated_at: "2026-07-10T08:30:00Z",
  },
  {
    id: 14,
    judul: "Jadwal Ujian Susulan",
    ringkasan: "Informasi ujian susulan bagi yang berhalangan",
    isi: "Ujian susulan akan dilaksanakan pada tanggal 8-9 Desember 2026. Siswa yang berhalangan hadir pada ujian utama wajib mengurus surat izin dan mengikuti ujian susulan.",
    kategori: "Assessment",
    target: "Siswa",
    status: "Draft",
    penulis: "Asep Nugraha",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-12-01",
    created_at: "2026-11-25T11:00:00Z",
    updated_at: "2026-11-25T11:00:00Z",
  },
  {
    id: 15,
    judul: "Libur Hari Raya Idul Fitri",
    ringkasan: "Libur dalam rangka Idul Fitri",
    isi: "Libur Hari Raya Idul Fitri 1448 H akan berlangsung dari tanggal 15-18 November 2026. Kegiatan belajar mengajar akan kembali aktif pada tanggal 19 November 2026.",
    kategori: "Libur",
    target: "Semua Pengguna",
    status: "Dipublikasikan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-10-20",
    created_at: "2026-10-20T08:00:00Z",
    updated_at: "2026-10-20T08:00:00Z",
  },
  {
    id: 16,
    judul: "Rapat Orang Tua/Wali Siswa",
    ringkasan: "Undangan rapat orang tua/wali siswa",
    isi: "Rapat orang tua/wali siswa akan dilaksanakan pada tanggal 12 September 2026. Pembahasan meliputi perkembangan belajar siswa dan program sekolah ke depan.",
    kategori: "Informasi Umum",
    target: "Semua Pengguna",
    status: "Diarsipkan",
    penulis: "Kepala Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-09-01",
    created_at: "2026-09-01T07:00:00Z",
    updated_at: "2026-09-01T07:00:00Z",
  },
  {
    id: 17,
    judul: "MPLS Siswa Baru Tahun Ajaran 2026/2027",
    ringkasan: "Masa Pengenalan Lingkungan Sekolah",
    isi: "MPLS untuk siswa baru kelas X akan dilaksanakan pada tanggal 14-18 Juli 2026. Seluruh siswa baru wajib mengikuti rangkaian kegiatan MPLS.",
    kategori: "Kegiatan Sekolah",
    target: "Siswa",
    status: "Diarsipkan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [
      { id: 1, nama: "jadwal-mpls-2026.docx", ukuran: "540 KB", tipe: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
    ],
    tanggal_publish: "2026-07-01",
    created_at: "2026-07-01T09:00:00Z",
    updated_at: "2026-07-01T09:00:00Z",
  },
  {
    id: 18,
    judul: "Informasi Beasiswa Prestasi",
    ringkasan: "Pendaftaran beasiswa bagi siswa berprestasi",
    isi: "Sekolah membuka pendaftaran beasiswa prestasi untuk siswa berprestasi akademik dan non-akademik. Pendaftaran dibuka sampai 31 Agustus 2026. Persyaratan lengkap dapat diambil di bagian kesiswaan.",
    kategori: "Informasi Umum",
    target: "Siswa",
    status: "Dipublikasikan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [
      { id: 1, nama: "formulir-beasiswa.pdf", ukuran: "320 KB", tipe: "application/pdf" },
    ],
    tanggal_publish: "2026-08-01",
    created_at: "2026-08-01T08:00:00Z",
    updated_at: "2026-08-01T08:00:00Z",
  },
  {
    id: 19,
    judul: "Peringatan Hari Guru Nasional",
    ringkasan: "Kegiatan peringatan Hari Guru",
    isi: "Peringatan Hari Guru Nasional akan dilaksanakan pada tanggal 25 November 2026. Acara akan dimeriahkan dengan berbagai penampilan dari siswa.",
    kategori: "Kegiatan Sekolah",
    target: "Semua Pengguna",
    status: "Dipublikasikan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-11-10",
    created_at: "2026-11-10T08:00:00Z",
    updated_at: "2026-11-10T08:00:00Z",
  },
  {
    id: 20,
    judul: "Sosialisasi Program Jurusan BDP",
    ringkasan: "Sosialisasi program jurusan Bisnis Daring dan Pemasaran",
    isi: "Jurusan BDP akan mengadakan sosialisasi program pada tanggal 5 Agustus 2026. Acara ini bertujuan untuk memperkenalkan program dan peluang karir di bidang bisnis digital.",
    kategori: "Akademik",
    target: "BDP",
    status: "Draft",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-08-05",
    created_at: "2026-08-01T10:00:00Z",
    updated_at: "2026-08-01T10:00:00Z",
  },
  {
    id: 21,
    judul: "Jadwal Ekstrakurikuler Semester Ganjil",
    ringkasan: "Jadwal kegiatan ekstrakurikuler semester ini",
    isi: "Jadwal ekstrakurikuler untuk semester ganjil sudah diterbitkan. Kegiatan dilaksanakan setiap hari Selasa dan Kamis mulai pukul 15.30. Silakan pilih ekstrakurikuler yang diminati.",
    kategori: "Pembelajaran",
    target: "Siswa",
    status: "Dipublikasikan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-07-20",
    created_at: "2026-07-20T09:00:00Z",
    updated_at: "2026-07-20T09:00:00Z",
  },
  {
    id: 22,
    judul: "Libur Nasional Bulan Agustus",
    ringkasan: "Informasi hari libur nasional bulan Agustus",
    isi: "Bulan Agustus terdapat hari libur nasional yaitu Hari Kemerdekaan RI pada 17 Agustus. Kegiatan belajar mengajar tetap berjalan seperti biasa di luar tanggal tersebut.",
    kategori: "Libur",
    target: "Semua Pengguna",
    status: "Diarsipkan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-07-25",
    created_at: "2026-07-25T08:00:00Z",
    updated_at: "2026-07-25T08:00:00Z",
  },
  {
    id: 23,
    judul: "Asesmen Sumatif Kelas XII",
    ringkasan: "Pelaksanaan asesmen sumatif kelas XII",
    isi: "Asesmen sumatif untuk siswa kelas XII akan dilaksanakan pada tanggal 13-17 April 2026. Hasil asesmen akan menjadi salah satu pertimbangan kelulusan.",
    kategori: "Assessment",
    target: "Siswa",
    status: "Diarsipkan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-04-01",
    created_at: "2026-04-01T08:00:00Z",
    updated_at: "2026-04-01T08:00:00Z",
  },
  {
    id: 24,
    judul: "Penutupan Pendaftaran PKL",
    ringkasan: "Batas akhir pendaftaran PKL",
    isi: "Pendaftaran PKL untuk semester genap akan ditutup pada 15 Februari 2026. Segera daftarkan diri melalui wali kelas masing-masing.",
    kategori: "PKL",
    target: "Jurusan Tertentu",
    status: "Diarsipkan",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-02-01",
    created_at: "2026-02-01T09:00:00Z",
    updated_at: "2026-02-01T09:00:00Z",
  },
  {
    id: 25,
    judul: "Perpanjangan Waktu Pendaftaran Lomba",
    ringkasan: "Pendaftaran lomba diperpanjang",
    isi: "Pendaftaran lomba peringatan HUT RI diperpanjang sampai 15 Agustus 2026. Manfaatkan kesempatan ini untuk berpartisipasi.",
    kategori: "Kegiatan Sekolah",
    target: "Siswa",
    status: "Draft",
    penulis: "Admin Sekolah",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-08-10",
    created_at: "2026-08-10T10:00:00Z",
    updated_at: "2026-08-10T10:00:00Z",
  },
  {
    id: 26,
    judul: "Perubahan Jadwal Praktikum TKJ",
    ringkasan: "Jadwal praktikum jaringan komputer kelas X TKJ 2 diubah",
    isi: "Praktikum jaringan komputer untuk kelas X TKJ 2 yang biasanya dilaksanakan hari Kamis, diubah menjadi hari Selasa mulai tanggal 1 September 2026. Hal ini dikarenakan laboratorium digunakan untuk asesmen.",
    kategori: "Pembelajaran",
    target: "Kelas Tertentu",
    kelas: "X TKJ 2",
    status: "Dipublikasikan",
    penulis: "Asep Nugraha",
    pinned: false,
    lampiran: [],
    tanggal_publish: "2026-08-28",
    created_at: "2026-08-28T07:45:00Z",
    updated_at: "2026-08-28T07:45:00Z",
  },
  {
    id: 27,
    judul: "Tugas Tambahan Bahasa Indonesia Kelas X",
    ringkasan: "Tugas tambahan untuk siswa kelas X TKJ 1",
    isi: "Tugas tambahan berupa membuat karangan dengan tema \"Pengalaman Belajar Jarak Jauh\" dikumpulkan paling lambat tanggal 15 September 2026 melalui wali kelas.",
    kategori: "Pembelajaran",
    target: "Kelas Tertentu",
    kelas: "X TKJ 1",
    status: "Dipublikasikan",
    penulis: "Siti Rahayu",
    pinned: false,
    lampiran: [
      { id: 1, nama: "panduan-tugas.docx", ukuran: "210 KB", tipe: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
    ],
    tanggal_publish: "2026-08-25",
    created_at: "2026-08-25T09:20:00Z",
    updated_at: "2026-08-25T09:20:00Z",
  },
]
