export {
  DUMMY_ANALYTICS_SUMMARY,
  DUMMY_ANALYTICS_BY_SUBJECT,
  DUMMY_ANALYTICS_BY_EXAM_TYPE,
  DUMMY_ANALYTICS_BY_CLASS,
  DUMMY_ANALYTICS_TIMELINE,
  DUMMY_TOP_PERFORMERS,
  DUMMY_STUDENTS_NEEDING_ATTENTION,
  DUMMY_ANALYTICS_INSIGHTS,
} from "@/features/analitik/dummy/analitik.data"
